-- seed.sql
-- RetroBoard: Optional seed data for local development
--
-- This file is executed by `supabase db reset` after all migrations.
-- Add sample boards, columns, cards, participants, votes, and action items
-- here for local development and testing.
--
-- Usage:
--   supabase db reset          -- runs migrations + this seed file
--   supabase db reset --no-seed -- runs migrations only
--
-- NOTE: IDs below should be nanoid-style TEXT strings matching the format
-- used by the application (e.g. 'board_abc123', 'col_xyz789').
-- Keep seed data idempotent where possible.

-- Example (uncomment and customize as needed):
--
-- INSERT INTO boards (id, title, template, created_by) VALUES
--   ('demo-board-001', 'Sprint 42 Retro', 'mad-sad-glad', 'participant-001');
--
-- INSERT INTO participants (id, board_id, display_name, is_admin) VALUES
--   ('participant-001', 'demo-board-001', 'Jordan', true),
--   ('participant-002', 'demo-board-001', 'Alex', false);
--
-- INSERT INTO columns (id, board_id, title, color, position) VALUES
--   ('col-mad-001',  'demo-board-001', 'Mad',  '#DC2626', 0),
--   ('col-sad-001',  'demo-board-001', 'Sad',  '#2563EB', 1),
--   ('col-glad-001', 'demo-board-001', 'Glad', '#16A34A', 2);
--
-- INSERT INTO cards (id, column_id, board_id, text, author_name, author_id, position) VALUES
--   ('card-001', 'col-mad-001',  'demo-board-001', 'Deployments were flaky this sprint', 'Jordan', 'participant-001', 0),
--   ('card-002', 'col-glad-001', 'demo-board-001', 'Shipped the new dashboard!',         'Alex',   'participant-002', 0);
--
-- INSERT INTO votes (card_id, board_id, voter_id) VALUES
--   ('card-002', 'demo-board-001', 'participant-001');
--
-- INSERT INTO action_items (board_id, description, assignee, status) VALUES
--   ('demo-board-001', 'Investigate CI flakiness', 'Jordan', 'open');
